version: '3'
services:
  redis:
    image: redis
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  master:
    build: .
    image: docker-ci
    depends_on:
      - redis
    ports:
      - "3000:3000"
    env_file:
      - env/prod.env
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  worker:
    image: docker-ci
    depends_on:
      - redis
    command: --worker
    volumes:
      - ./keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - env/prod.env
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

