version: '3'
services:
  redis:
    image: redis

  master:
    build: .
    image: docker-ci
    depends_on:
      - redis
    ports:
      - "3000:3000"
    env_file:
      - env/prod.env

  worker:
    image: docker-ci
    depends_on:
      - redis
    command: --worker
    volumes:
      - ./keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - env/prod.env


