version: '3'
services:
  docker-ci:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./docker-compose.env